### ISSUE TITLE
Missing channel in ApiPlatform

### ISSUE THREAD

**Issue by ivaskad** [monsieurbiz/SyliusAlertMessagePlugin#6]
I have created api routes for getting messages and found that channel relation is missing.

After little research i found that you use 'Channel' in relation instead of 'ChannelInterface'.

This fixed missing relation in ApiPlatform. 

https://github.com/monsieurbiz/SyliusAlertMessagePlugin/blob/d1d5640ed255027d2a98e8f76ef7f3111a3190c5/src/Entity/Message.php#L68

**Comment by maximehuran** [comment]
This issue is resolved now
